// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrv6EsdZnc5kmx_L8gz5_7NudJPMVnCiU',
    appId: '1:817134598826:web:ed35b2179227a4e4392ed3',
    messagingSenderId: '817134598826',
    projectId: 'fir-login-8e65d',
    authDomain: 'fir-login-8e65d.firebaseapp.com',
    storageBucket: 'fir-login-8e65d.appspot.com',
    measurementId: 'G-X86403300Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwITNs3z0j27kzwFHBKbgtChbfEmaV37Y',
    appId: '1:817134598826:android:7812fca3228b0f18392ed3',
    messagingSenderId: '817134598826',
    projectId: 'fir-login-8e65d',
    storageBucket: 'fir-login-8e65d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhTzzzAyNvwl0SX7vtSU6Cf6jw2D8CkGA',
    appId: '1:817134598826:ios:f31dcf060dabe426392ed3',
    messagingSenderId: '817134598826',
    projectId: 'fir-login-8e65d',
    storageBucket: 'fir-login-8e65d.appspot.com',
    iosClientId: '817134598826-bf80saugp9e4q4ako2nhvqg0pfm7fsgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhTzzzAyNvwl0SX7vtSU6Cf6jw2D8CkGA',
    appId: '1:817134598826:ios:f31dcf060dabe426392ed3',
    messagingSenderId: '817134598826',
    projectId: 'fir-login-8e65d',
    storageBucket: 'fir-login-8e65d.appspot.com',
    iosClientId: '817134598826-bf80saugp9e4q4ako2nhvqg0pfm7fsgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );
}
